# config file
debug: false
key: STICK
bonus_chest: true
tp_radius: 256
protect_blocks: true
require_spout: false
default_world: false
default_world_name: myridiculouslylongworldnameiscalledcuthbert
include_default_world: false
platform: false
chameleon: true
sfx: true
give_key: false
the_end: false
nether: false
use_worldguard: true
respect_worldguard: true
respect_towny: true
respect_worldborder: true
land_on_water: true
timeout: 5
timeout_height: 135
name_tardis: false
border_radius: 64
create_worlds: true
#rooms
rooms:
  PASSAGE:
    cost: 250
    seed: CLAY
  ARBORETUM:
    cost: 500
    seed: LEAVES
  BEDROOM:
    cost: 500
    seed: GLOWSTONE
  KITCHEN:
    cost: 500
    seed: PUMPKIN
  LIBRARY:
    cost: 500
    seed: BOOKSHELF
  POOL:
    cost: 500
    seed: SNOW_BLOCK
  VAULT:
    cost: 500
    seed: DISPENSER
#artron energy
player: 2
random: 25
travel: 50
comehere: 200
hide: 400
recharge_distance: 10
lightning_recharge: 100
creeper_recharge: 50
