# config file
debug: false
# how the plugin persists data
storage:
    database: sqlite
    mysql:
        url: mysql://localhost:3306/TARDIS
        user: bukkit
        password: mysecurepassword
# inner TARDIS
creation:
    create_worlds: true
    create_worlds_with_perms: false
    default_world: false
    default_world_name: myridiculouslylongworldnameiscalledcuthbert
    tips_limit: 400
    border_radius: 256
    gamemode: survival
    keep_night: true
    inventory_group: 0
    add_perms: true
    custom_schematic: false
    custom_schematic_seed: OBSIDIAN
    custom_creeper_id: 138
    use_block_stack: false
    use_clay: false
    count: 0
# outer TARDIS
police_box:
    name_tardis: false
    wall_id: 35
    wall_data: 11
    tardis_lamp: 50
    platform_id: 35
    platform_data: 8
    materialise: true
    confirm_timeout: 15
    sign_colour: WHITE
# travel settings
travel:
    include_default_world: false
    tp_radius: 500
    platform: false
    chameleon: true
    give_key: false
    the_end: false
    nether: false
    land_on_water: true
    timeout: 5
    timeout_height: 135
    random_attempts: 30
    exile: false
    per_world_perms: false
    terminal_step: 1
# general preferences
preferences:
    key: GOLD_NUGGET
    use_worldguard: true
    respect_worldguard: true
    respect_towny: nation
    respect_worldborder: true
    respect_factions: true
    sfx_volume: 10;
    difficulty: hard
    strike_lightning: true
    freeze_cooldown: 60
    hads_damage: 10
    hads_distance: 10
    malfunction: 3
    malfunction_end: 3
    malfunction_nether: 3
    use_default_condensables: true
    heal_speed: 200
# restrictions
allow:
    mob_farming: true
    spawn_eggs: true
    emergency_npc: true
    achievements: true
    autonomous: true
    hads: true
    tp_switch: true
    all_blocks: false
    sfx: true
    wg_flag_set: true
    zero_room: false
    external_gravity: false
# room related
growth:
    gravity_max_distance: 15
    gravity_max_velocity: 5
    return_room_seed: true
    rooms_require_blocks: false
    rooms_condenser_percent: 100
    room_speed: 4
# don't touch
conversions:
    conversion_done: true
    location_conversion_done: true
    uuid_conversion_done: true