# config file
debug: false
key: STICK
bonus_chest: true
tp_radius: 256
protect_blocks: true
require_spout: false
default_world: false
default_world_name: world
include_default_world: false
platform: false
chameleon: true
sfx: true
give_key: false
the_end: false
nether: false
land_on_water: true